version: "3.9"

services:
  # Servidor TCP que aceptar√° conexiones de workers
  api:
    build:
      context: .
      dockerfile: api-coordinator/Dockerfile
    env_file: ./deploy/env/api.env
    ports:
      - "8000:80"   #HTTP
      - "9090:9000" #TCP
    volumes:
      - ./dataset:/app/dataset:ro
    environment:
      COORDINATOR_ADDR: ":9000"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - internal

  # Workers que se conectan a api:9090
  worker1:
    build:
      context: .
      dockerfile: worker-node/Dockerfile
    env_file: ./deploy/env/worker.env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - internal

  worker2:
    build:
      context: .
      dockerfile: worker-node/Dockerfile
    env_file: ./deploy/env/worker.env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - internal

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:

volumes:
  mongo_data:
