version: "3.9"

services:
  # Servidor TCP que aceptar√° conexiones de workers
  api:
    build:
      context: .
      dockerfile: api-coordinator/Dockerfile
    env_file: ./deploy/env/api.env
    ports:
      - "8000:80"
      - "9090:9000"
    environment:
      COORDINATOR_ADDR: ":9000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - internal

  # Workers que se conectan a api:9090
  worker1:
    build:
      context: .
      dockerfile: worker-node/Dockerfile
    env_file: ./deploy/env/worker.env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - internal

  worker2:
    build:
      context: .
      dockerfile: worker-node/Dockerfile
    env_file: ./deploy/env/worker.env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - internal

  mongo:
    image: mongo:8.0
    command: ["mongod", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: default
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      internal:
        aliases:
          - mongo 

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:

volumes:
  mongo_data:
